/** Auto-generated by npm run build:env — do not edit by hand */
(function (w) {
  'use strict';
  w.__MINTRAIQ_ENV__ = {"logtoEndpoint":"https://ufq3nf.logto.app","logtoAppId":"jj76jvuz39xoys68ys7ly","financeApiBase":"http://127.0.0.1:5000/api","financeApiResource":"https://api.finance-ai.suite.com","signInRedirectUri":"","legacyFlaskBase":"http://127.0.0.1:5000","fastApiDocsUrl":"http://127.0.0.1:5000/api/docs"};
})(typeof window !== 'undefined' ? window : this);
